template: Hello, %s!
defaultName: Stranger
# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: PASSWORD
    # the JDBC URL; the database is called DWGettingStarted
    url: CONNECTION_STRING
    # any properties specific to your JDBC driver:
    properties:
      charSet: UTF-8
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

swagger:
    resourcePackage: com.goranzuri.anime.api